export enum ERROR_TYPE {
  USE_COLOR_THEME_OUTSIDE_COLOR_PROVIDER = 'USE_COLOR_THEME_OUTSIDE_COLOR_PROVIDER',
  STORAGE_KEY_DUPLICATE = 'STORAGE_KEY_DUPLICATE',
  THEME_KEY_NOT_FOUND = 'THEME_KEY_NOT_FOUND',
}
